name: lazy-k
version: 0.1.0.0
github: 'ghaaj/lazy-k'
license: BSD-3-Clause
author: 'ghaaj'
maintainer: '91141283+ghaaj@users.noreply.github.com'
copyright: '2024 ghaaj'

extra-source-files:
    - README.md
    - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ghaaj/lazy-k#readme>

dependencies:
    - base >= 4.7 && < 5
    - ansi-terminal
    - haskeline
    - text
    - unix
    - megaparsec

ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Wpartial-fields
    - -Wredundant-constraints

library:
    source-dirs: src

executables:
    lazy-k-exe:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - lazy-k

tests:
    lazy-k-test:
        main: Spec.hs
        source-dirs: test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - lazy-k
